version: '3'

services:
  app:
    build: .
    environment:
      DB_URL: jdbc:postgresql://postgresql/twarc_test
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgresql      
  postgresql:
    image: postgres:12-alpine
    
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twarc_test
